### ISSUE TITLE
How to complete DockProgress in 4.3.0 version

### ISSUE THREAD

**Issue by Kyle-Ye** [sindresorhus/DockProgress#20]
In the 3.2.0 version, if we set the progress value to "1.0". The extra dock progress will be hidden.

https://github.com/sindresorhus/DockProgress/blob/7100b68571e2dafe3a06ad5905b80fc3b0107b4b/Sources/DockProgress/DockProgress.swift#L79

The above logic does not seem to have been retained in the latest version 4.3.0.

Related Issue: https://github.com/XcodesOrg/XcodesApp/issues/529#issuecomment-2017401127

**Comment by sindresorhus** [comment]
Would you be able to try out this commit? https://github.com/sindresorhus/DockProgress/commit/d4f23b5a8f5ca0fac393eb7ba78c2fe3e32e52da

**Comment by Kyle-Ye** [comment]
> Would you be able to try out this commit? [d4f23b5](https://github.com/sindresorhus/DockProgress/commit/d4f23b5a8f5ca0fac393eb7ba78c2fe3e32e52da)

Tried it. It works. 

Would you minding releasing a new version (eg. 4.3.1 or 4.4.0) for it? Thanks

See https://github.com/XcodesOrg/XcodesApp/pull/545

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/DockProgress/releases/tag/4.3.1
