### ISSUE TITLE
MacOS 10.14 Icon transparency

### ISSUE THREAD

**Issue by NuroDev** [sindresorhus/DockProgress#4]
Am testing first 10.14 beta and noticed that the dock icon for [Gifski](https://github.com/sindresorhus/gifski-app) during gif conversion resulted in the icon being 100% transparent(Invisible) and did not reset until app restart.

<img width="519" alt="screenshot 2018-06-11 at 04 48 14" src="https://user-images.githubusercontent.com/4991309/41211967-be0c36c0-6d32-11e8-89bb-b47bcb3e2eec.png">
<img width="612" alt="screenshot 2018-06-11 at 04 48 32" src="https://user-images.githubusercontent.com/4991309/41211968-be26c602-6d32-11e8-8006-0d095e25035a.png">

I know not priority as still beta MacOS version, but still worth reporting.

**Comment by sindresorhus** [comment]
I cannot reproduce this in Mojave beta 11.
